---
- name: Install minio helm chart
  helm:
    host: "{{ l_helm_host }}"
    port: "{{ l_helm_port }}"
    chart:
      name: minio
      version: "{{ spinnaker_minio_chart_version }}"
      source:
        type: repo
        location: https://kubernetes-charts.storage.googleapis.com
    values: "{{ spinnaker_minio_chart_values }}"
    state: present
    name: "{{ spinnaker_minio_release_name }}"
    namespace: "{{ spinnaker_namespace }}"
