---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: rancher
    box: centos/7
    cpus: 1
    memory: 4096
    interfaces:
      - auto_config: true
        ip: 172.28.128.3
        network_name: private_network
        type: static
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      rancher:
        rke_nodes:
          - address: 172.28.128.3
            user: vagrant
            role: [controlplane, etcd, worker]
  lint:
    name: ansible-lint
    options:
      x: [
        "204"  # Lines should be no longer than 160 chars
      ]
verifier:
  name: testinfra
  lint:
    name: flake8
